package.json, src/pages/MapPage/components/Mission/MissionDrawer/MissionStep2/MissionStep2.js, src/pages/MapPage/contexts/MissionContext.js
* Fix floor picker bug
* change floor value to string
* Add condition check in MissionContext
* Add babel-eslint
=> Fix floor-picker can't choose b1 b2

src/pages/MapPage/hooks/useTagList.js
* Fix can't query tag list problem
* Rename tagRenderList to unarchivedTagList
=> Fix tag list query

src/pages/MapPage/components/Mission/MissionDrawer/MissionStep2/MissionStep2.js, src/pages/MapPage/constants/missionInfo.js
Fixes #24 
* Because  MissionStep2 mission's name was wrong
* Modify MissionStep2.js and missionInfo.js to print correct mission's name
=> Fix MissionStep2 print wrong mission name 

src/pages/MapPage/components/Mission/MissionDrawer/MissionStep1/MissionStep1.js, src/pages/MapPage/components/TagDetail/DetailPart.js
* Let Geocoding more accurate
* Fix tag archive message description
* Assign result_type to premise
=> Add geocoding premise param

src/pages/MapPage/components/GuidePage/GuidePage.js, src/pages/MapPage/components/TagDetail/DetailPart.js
* Fixes #23 
* Disable open GuidePage when width is over 'sm'
* Open a SnackBar notification message
=> Disable guide page open on desktop

src/pages/MapPage/components/Map/Map.js
* Add Google Map Marker Clustering
* Add MarkerClusterer in Map.js
- https://react-google-maps-api-docs.netlify.app/#markerclusterer
=> Add google map marker clustering

src/pages/MapPage/Mutation/useVoteTag.js, src/pages/MapPage/components/GuidePage/GuidePage.js, src/pages/MapPage/components/Mission/ImageUpload.js, src/pages/MapPage/components/Mission/MissionDrawer/MissionStep2/MissionStep2.js, src/pages/MapPage/components/TagDetail/DetailPart.js, src/pages/MapPage/components/TagDetail/TagDetailDialog.js, src/pages/MapPage/contexts/MissionContext.js, src/pages/MapPage/contexts/TagContext.js, src/pages/MapPage/hooks/useThreshhold.js
* Get threshold from backend.
* Add useThreshold hook
* Remove all unused console log.
=> Add get threshold from backend

src/pages/MapPage/components/Mission/MissionDrawer/MissionStep2/MissionStep2.js, src/pages/MapPage/components/Mission/MissionDrawer/MissionStepper.js, src/pages/MapPage/contexts/MissionContext.js
Fixes #35 
* We need to remind user have undone field
* Add parameter in MissionContext to check user have which field need to fill and remind user with red box
=> Remind user undone button

src/pages/MapPage/components/Mission/MissionDrawer/MissionStep2/MissionStep2.js
Fixes #31 
* Fix Mission Report Edit Icon Style was wrong 
* Change Mission Report Edit Icon position
=> Fix Mission Report Edit Icon Style

src/pages/MapPage/components/TagDetail/DetailPart.js
* Because when mission state is to be processed vote should be locked
* Vote will appear when mission processed
=> When mission state is to be processed vote will be locked

src/pages/MapPage/MapPage.js, src/pages/MapPage/components/GuidePage/GuidePage.js, src/utils/contexts/MissionContext.js, src/utils/contexts/TagContext.js, src/utils/hooks/useTagList.js
* Add timeout for query tag list data
* Implement a while function which query tag list every 30 seconds
* Refactor tag list query flow
=> Add timeout for query tagList

src/pages/MapPage/MapPage.js
* Remove tag list auto update process
*
=> Remove taglist auto update

src/pages/MapPage/components/Map/Map.js
* Add google map default icon
* Filter all besides school and sport.
=> Add default school and sport icon on map

src/pages/MapPage/MapPage.js, src/pages/MapPage/components/Map/Map.js, src/pages/MapPage/components/Mission/MissionDrawer/MissionDrawer.js, src/pages/MapPage/components/Mission/MissionDrawer/MissionStep0/MissionStep0.js, src/pages/MapPage/components/Mission/MissionDrawer/MissionStep2/MissionStep2.js, src/pages/MapPage/components/TagDetailDrawer/DetailPart.js, src/pages/MapPage/components/TagDetailDrawer/TagDetailDrawer.js, src/utils/contexts/MissionContext.js, src/utils/contexts/TagContext.js, src/utils/hooks/useMenu.js, src/utils/hooks/useStep.js, src/utils/hooks/useTagDetail.js, src/utils/hooks/useUserTags.js
* Optimize rerendering process loading
* use useCallback and useMemo hooks to reduce redundant rendering
=> Optimize rerendering process

src/utils/contexts/MissionContext.js
* statusName field is missing
*
=> Fix statusName field missing bug

.eslintrc, src/constants/missionInfo.js, src/constants/tagData.js, src/pages/MapPage/components/Mission/MissionDrawer/MissionStep0/MissionStep0.js, src/pages/MapPage/components/Mission/MissionDrawer/MissionStep2/MissionStep2.js, src/pages/MapPage/components/TagDetailDrawer/TagDetailDrawer.js, src/utils/contexts/MissionContext.js
* We add Dynamic-mission let user can choose
* Allow users to choose dynamic mission, and modify the return mode of status
=> Add Dynamic-mission

yarn.lock
=> Fix dependency alert

src/App.js, src/pages/MapPage/components/Mission/MissionDrawer/MissionStep2/MissionStep2.js, src/utils/contexts/MissionContext.js
* Fix button type in missionStep2
* Fix default status for mission 1 & 2
* Move emulator url into env
- Please add this line in `.env` file `REACT_APP_FIREBASE_EMULATER_URL="http://0.0.0.0:9099"`
=> Fix  button color & default status & emulator url

src/pages/MapPage/components/Map/Map.js, src/utils/hooks/useTagList.js
* Fix incorrect schema for new tag list query schema
* Remove accessibility field
=> Fix tag list query schema to new backend in dev

src/utils/contexts/MissionContext.js
* Fix check next step for the third mission
* Do not initial subOptionId while missionId changed
=> Fix check next step

src/pages/MapPage/MapPage.js, src/pages/MapPage/components/SearchBar/SearchBarMenu.js, src/pages/MapPage/components/TagDetailDrawer/DetailPart.js, src/pages/MapPage/components/UserDialog/UserDialog.js, src/utils/contexts/UserContext.js, src/utils/hooks/useTagDetail.js, src/utils/hooks/useUserDetail.js
*This pull request adds a new hook "useUserDetail.js". It makes query on "getUserData" and return user's detail data.
*
=> Feature/add use user detail.js

src/constants/envValues.js, src/utils/grahpql.js
=> Add env for subscription

src/pages/MapPage/components/Mission/MissionDrawer/MissionStep1/MissionStep1.js, src/pages/MapPage/components/UserDialog/UserDialog.js, src/utils/hooks/useUserDetail.js
* Fix userAddTagNumber not update
* Fix typo error
*
=> Fix userAtagNumber not update

src/pages/MapPage/MapPage.js, src/pages/MapPage/components/LocationFab/LocationFab.js, src/pages/MapPage/components/Map/Map.js, src/pages/MapPage/components/Mission/MissionDrawer/MissionDrawer.js, src/pages/MapPage/components/TagDetailDrawer/DetailPart.js, src/pages/MapPage/components/TagDetailDrawer/TagDetailDrawer.js, src/utils/contexts/MissionContext.js, src/utils/contexts/TagContext.js, src/utils/contexts/UserContext.js, src/utils/hooks/useMenu.js, src/utils/hooks/useStep.js, src/utils/hooks/useTagList.js, src/utils/hooks/useUserTags.js, src/utils/hooks/useViewCount.js
=> Fix useffect problem

src/App.js, src/utils/contexts/UserContext.js
* Add user checking on main page before entering login page
* Check user is null or undefine
=> Add user check on main page

src/App.js, src/pages/MapPage/components/Filter/FilterDrawer.js, src/pages/MapPage/components/UserDialog/UserDialog.js, src/utils/hooks/useUserDetail.js
* Add loading dialog for use dialog
*
=> Add loading dialog for use dialog

src/utils/contexts/MissionContext.js, src/utils/hooks/useTagList.js
* Tag wasn't updated after updating tag's location
* Add update litener
Fix #91
=> Fix location wasn't updated

src/pages/MapPage/components/TagDetailDrawer/DetailPart.js
* Fix date time
* Exchange two date
Fix #95
=> Change date time

src/pages/MapPage/components/Map/Map.js
=> Put on all icon on map

src/utils/hooks/useViewCount.js
* Fix view count looping
* add usecallback
=> Fix view count looping

src/utils/contexts/UserContext.js
* Auto-refresh token every 15 minutes
* Setup timeout function
=> Add refresh token process

src/constants/missionInfo.js
* Change Wi-Fi name from NTCU to NYCU
* Change text in the missionInfo,js
=> Change Wi-Fi name from NTCU to NYCU

.github/workflows/CI.yml, package.json, src/pages/MapPage/components/Map/Map.js, src/pages/MapPage/components/TagDetailDrawer/DetailPart.js
* Add CI process
* Add CI github action
=> Fix eslint and add CI action

.github/workflows/deploy.yml, README.md
=> Add fe doc

src/constants/missionInfo.js
* Fix  #105 
* Add new text in the missionInfo.js
=> Add new type Dynamic Mission GymCrowd

src/pages/MapPage/components/ReportHistory/ReportHistory.js, src/utils/contexts/MissionContext.js, src/utils/contexts/TagContext.js, src/utils/hooks/useUserTags.js
* Fix user report wasn't updated
* add useEffect
=> Fix user report wasn't updated

src/utils/hooks/useTagDetail.js
* Fix #104 
* Add token if login
=> fix vote button wasn't updated

src/utils/contexts/UserContext.js, src/utils/functions/localStorage.js
* Store token expire timestamp in local storage
*
=> Add token expire info in localstorage

yarn.lock
=> Fix dependencies alert

src/utils/contexts/UserContext.js
* Fix refresh token recursive
*
=> fix refresh token recursive

package.json, src/assets/images/searchPositionIcon.svg, src/constants/mapConstants.js, src/pages/MapPage/MapPage.js, src/pages/MapPage/components/Map/Map.js, src/pages/MapPage/components/SearchBar/SearchBar.js, yarn.lock
* Add searchFunction
* We use usePlacesWidget to autocompelete search
=> Resend whis function branch

src/App.js, src/pages/MapPage/MapPage.js, src/pages/MapPage/components/Map/Map.js, src/pages/MapPage/components/ReportHistory/ReportHistory.js, src/utils/WindowBackProvider.js
* Add active tag id in route
* Add react router dom params :activeTagId
=> Add active tag id on url

src/utils/contexts/TagContext.js, src/utils/hooks/useTagList.js
=> Fix pagination

src/pages/MapPage/components/Map/Map.js, src/pages/MapPage/components/SearchBar/SearchBar.js
* Search Advice will present when close searchBar
* Use showcontrol to control advice present
=> Fix searchAdvice present when close searchBar

public/index.html
* Lock user scalable while using PWA
*
=> Lock user scalable

src/pages/MapPage/MapPage.js
* Fix position rerender
* set position follow to false
=> Fix position rerender

src/pages/MapPage/components/Filter/FilterFab.js, src/pages/MapPage/components/SearchBar/SearchBar.js
* Let filter default on try to let user find this function
* Add new quick button && filter open default true
=> Let filter default open && change quick button

src/pages/MapPage/components/SearchBar/SearchBar.js
* We need to limit search range in NCTU
* We add judge after search
=> Limit  search range in NCTU

src/pages/MapPage/components/TagDetailDrawer/DetailPart.js
* Fx time display on tag detail drawer
=> Fix tag detail time display wrong

src/pages/MapPage/MapPage.js, src/pages/MapPage/components/GuidePage/GuidePage.js
* Fix guide page can't show up 
* Add skip state to determine whether to skip the guide page
=> Fix guide can't show up after login

src/pages/MapPage/components/Map/Map.js
* Fix filter not work after updating to new cluster library
* Re-clean and add markers while shown tag change.
=> Fix filter bug after updating to new cluster library

src/pages/MapPage/components/Mission/MissionDrawer/MissionStep2/MissionStep2.js, src/utils/contexts/MissionContext.js
* Fix edit tag info missing
* Prevent clean mission info when 'handleBack' and 'handleCangeMissionId'
=> Fix edit tag info miss bug

src/pages/MapPage/MapPage.js, src/pages/MapPage/components/Map/Map.js, src/pages/MapPage/components/TagDetailDrawer/TagDetailDrawer.js, src/utils/contexts/TagContext.js, src/utils/hooks/useDeleteTag.js, src/utils/hooks/useTagList.js
* Add delete tag button
* Add useDeleteTag hook
=> Add delete tag button

src/pages/MapPage/components/TagDetailDrawer/TagDetailDrawer.js
* Add confirm dialog while deleting tag
*
=> Add confirm dialog while deleting tag

yarn.lock
=> Fix dependency

src/utils/contexts/TagContext.js, src/utils/hooks/useTagList.js
* Fix user add tags not update after deleting tag
* Filter tags by id
=> Fix user add tags not update after deleting tag

src/pages/MapPage/components/TagDetailDrawer/DetailPart.js, src/utils/hooks/useTagDetail.js
* Fix user portfolio id inaccurate
*
=> Fix user portfolio inaccurate

src/pages/MapPage/components/SearchBar/SearchBar.js
* Because we want to close suggestion after close search bar and auto choose first one when user push enter
* Use constant (showcontrol) to control whether focus on input and use alert to tell user please choose suggestion because we can't auto choose first now
=> Tell user that we only can choose suggestion ,can't use enter to search

src/utils/hooks/useTagList.js
* Fix tag twinkling
* Add tag list cache
=> Fix tag twinkling

src/index.css, src/pages/MapPage/components/Filter/FilterFab.js, src/utils/hooks/useTagList.js
* Fix firefox scrollbar bug
* Fix scrollbar with css
=> Fix firefox scrollbar

src/pages/MapPage/components/Filter/FilterFab.js
=> Revise tag filter description

src/constants/missionInfo.js, src/pages/MapPage/components/Filter/FilterFab.js, src/pages/MapPage/components/GuidePage/GuidePageStep3.js, src/pages/MapPage/components/Mission/MissionDrawer/MissionDrawer.js, src/pages/MapPage/components/Mission/MissionDrawer/MissionStepper.js
* Rename our mission
* We change mission to report make user easy to know
=> Change name from mission to report

src/pages/MapPage/components/Map/Map.js
* Show position name to user  
*  We add position name on the top of label
=> Add position name on the seaech position icon

src/pages/MapPage/components/Map/Map.js
* Map can't show because call fixedTag before map load finish
* Add check before Marker
=> Fix new map bug

src/pages/MapPage/components/Map/Map.js
* Fixed code error in the map.js
* Remove fixedTag.length in the map.js
=> Fix map bug error

src/pages/MapPage/components/Map/Map.js
* #173 
* Remove check in fixedTag
=> Fix bug about filter can't know missionname

src/pages/MapPage/components/Filter/FilterFab.js, src/pages/MapPage/components/FixedTagDetailDrawer/FixedTagDetailPart.js
* Fix button in error position
* fix Grid in fixedTagDetail.js
=> Fix filter have overflow and fix button position

src/pages/MapPage/components/FixedTagDetailDrawer/FixedTagDetailPart.js
* Too more white place in the fixedTagDrawer
* fix margin in the Grid
=> Fix too more white in the fixedTagDrawer

.github/workflows/deploy.yml, .github/workflows/predeploy.yml
> :warning: **IMPORTANT: Do not merge this pull request until the necessary repository secrets have been added.**
* Current **deploy** and **predeploy** actions seems to be deprecated and not working well (refer to [this workflow run](https://github.com/CAMPUS-NYCU/SmartCampus/actions/runs/4524691131/jobs/7968686641)).
* This **deploy** and **predeploy** actions may work. I have made a testing in my fork repository and the result seems good.
*
=> Fix deploy and predeploy actions to ensure successful deployment

src/components/CustomDrawer/CustomDrawer.js, src/pages/MapPage/MapPage.js, src/pages/MapPage/components/Mission/MissionListDrawer/MissionListDrawer.js, src/pages/MapPage/components/Mission/MissionListDrawer/index.js, src/pages/MapPage/components/Mission/MissionListDrawer/missionList.js, src/pages/MapPage/components/Mission/MissionListFab/MissionListFab.js, src/pages/MapPage/components/Mission/MissionListFab/index.js
* Add feature to display list of missions which is requested for research purpose.
*
=> Add feature to display list of missions

src/pages/MapPage/MapPage.jsx
* Research targets mobile devices.
*A modal show in map page when non-mobile device detected.
=> feat(Research): :lock: Require mobile for map page

src/pages/MapPage/components/FixedTagDetailDrawer/FixedTagDetailDrawer.jsx, src/pages/MapPage/components/FixedTagDetailDrawer/FixedTagDetailPart.jsx
* To meet research 1 design
* [fixed tag combine floors](https://github.com/CAMPUS-NYCU/SmartCampus/commit/6b3a70679aaa642d71088ae8927d562f1fc62d8c)
=> fixed tag combine floors

src/pages/MapPage/MapPage.jsx, src/pages/MapPage/components/FixedTagDetailDrawer/FixedTagDetailPart.jsx, src/utils/contexts/TagContext.jsx, src/utils/hooks/useFixedTagDetail.jsx
* To meet Research 1 design.
Commits:
* [reset active tag and active fixed tag when close drawer](https://github.com/CAMPUS-NYCU/SmartCampus/commit/d957a7ff1126337195d278621217d20a9073f995)
* [empty if no data](https://github.com/CAMPUS-NYCU/SmartCampus/commit/03e262461e089b0f88d55581bcafae4f94755a53)
=> Mission step optimize

src/utils/hooks/useTagDetail.jsx, src/utils/hooks/useTagsSubscription.jsx
=> Research/add fixedTagId for useTag Data

src/pages/MapPage/components/TagDetailDrawer/ChangeStatus.jsx, src/pages/MapPage/components/TagDetailDrawer/TagDetailDrawer.jsx
* fix undefined array reading map in ChangeStatus
*
=> fix undefined array reading map (thisStatusType)

src/pages/MapPage/components/TagDetailDrawer/ChangeStatus.jsx, src/pages/MapPage/components/TagDetailDrawer/DetailPart.jsx, src/pages/MapPage/components/TagDetailDrawer/TagDetailDrawer.jsx
=> handle undefined

src/pages/MapPage/components/FixedTagDetailDrawer/FixedTagDetailPart.jsx, src/pages/MapPage/components/Mission/MissionDrawer/MissionStep2/MissionStep2.jsx, src/pages/MapPage/components/TagDetailDrawer/DetailPart.jsx, src/pages/MapPage/components/TagDetailDrawer/TagDetailDrawer.jsx, src/utils/hooks/useFixedTagList.jsx
* 增加根據 user number (實驗分組) 取得fixedtag 內容
*
=> get fixedtags through user Number done

src/utils/hooks/useFixedTagList.jsx
=> fix null regex

src/assets/images/res1-statusMarkerCleanActivated.svg, src/assets/images/res1-statusMarkerCrowdActivated.svg, src/assets/images/res1-statusMarkerFunctionActivated.svg, src/assets/images/res1-statusMarkerMaintenanceActivated.svg, src/assets/images/res1-statusMarkerNoiseActivated.svg, src/assets/images/res1-statusMarkerOccupationActivated.svg, src/assets/images/res1-statusMarkerOutlookActivated.svg, src/assets/images/res1-statusMarkerThermalComfortActivated.svg, src/assets/images/res1-statusMarkerUsageActivated.svg, src/constants/res1ReferMarkers.jsx, src/pages/MapPage/components/FixedTagDetailDrawer/FixedTagDetailPart.jsx, src/pages/MapPage/components/ReferMarkerFab/AllReferMarkers.jsx
=> Fix regex for new location name

src/constants/res1StatusType.jsx, src/pages/MapPage/components/Map/Map.jsx, src/pages/MapPage/components/TagDetailDrawer/TagDetailDrawer.jsx
* commit viewcount(in TagDetailDrawer). we don't need it in research
* rename statustype from 維護 to 保養
*
=> status marker done; and fix some errors

src/components/CustomDrawer/CustomDrawer.jsx, src/constants/res1CreateOptions.jsx, src/pages/MapPage/components/Mission/MissionDrawer/MissionStep2/MissionStep2.jsx
=> remove drawer minHeight; fix floor of created reports have no 'F'

src/pages/MapPage/components/Mission/MissionDrawer/MissionStepper.jsx, src/pages/MapPage/components/TagDetailDrawer/ChangeStatus.jsx, src/utils/contexts/TagContext.jsx, src/utils/hooks/useFixedTagList.jsx, src/utils/hooks/useTagList.jsx
=> Filter tags

src/constants/res1CreateOptions.jsx
=> categoryType modification

src/pages/MapPage/components/ReferMarkerFab/AllReferMarkers.jsx, src/utils/contexts/MissionContext.jsx
=> fix yellow-flag while creating report; modify zindex of refer-markers

src/utils/contexts/MissionContext.jsx
=> Upper shift hightlighted tag data

src/utils/contexts/MissionContext.jsx
=> fix getBounds() error

src/utils/contexts/MissionContext.jsx
* 修改 access getBounds() 資料的方式，以解決 getBounds() object 屬性會一直更名的問題
*
=> stringify then parse getBounds()
